server: Add remaining support for simple copy/paste
any1/neatvnc pull request #44
Opened 2020-09-16 22:19 UTC by soreau

- Add function to set callback for client_cut_text
- Add server_cut_text structure and function

2020-09-17 10:27 UTC, any1 commented
Nice! The rest of the code has `{` on the same line as `if` and `while`. Can you fix that for this and the wayvnc PR also?

2020-09-17 10:33 UTC, any1 commented
Also, we don't use `{ }` when there's only a single line in the code block, so prefer
```
if (stuff)
    do_stuff();
```

2020-09-17 20:35 UTC, soreau commented
> Nice! The rest of the code has `{` on the same line as `if` and `while`. Can you fix that for this and the wayvnc PR also?
> Also, we don't use `{ }` when there's only a single line in the code block, so prefer
> 
> ```
> if (stuff)
>     do_stuff();
> ```

These should be fixed now.

2020-09-18 10:59 UTC, any1 requested changes

2020-09-18 10:59 UTC, any1 commented on include/common.h
> +	nvnc_client_cut_fn client_cut_fn;
What scenario do you have in mind where it's useful to be able to set a per-client cut text callback?

2020-09-18 10:59 UTC, any1 commented on include/neatvnc.h
> +typedef void (*nvnc_client_cut_fn)(struct nvnc_client*, char* data, uint32_t len);
`data` should be `const`. The word "data" is such a generic word, would it not be more fitting to call this "text"? Why is there a length parameter? Can this not be a zero terminated string?

2020-09-18 10:59 UTC, any1 commented on include/neatvnc.h
> +void nvnc_set_data_transfer_fn(struct nvnc* self, nvnc_client_cut_fn fn);
Why not `nvnc_set_client_cut_fn`?

2020-09-18 10:59 UTC, any1 commented on include/neatvnc.h
> +void _nvnc_server_cut_text(struct nvnc_display*, char *text, uint32_t length);
text should be const and the star should be on the left side of the space. Also, does there need to be length? `_nvnc_server_cut_text` should not be here as it is not a public API function.

2020-09-18 10:59 UTC, any1 commented on include/rfb-proto.h
> +	char data[0];
Same as before, I prefer the word "text".

2020-09-18 10:59 UTC, any1 commented on include/rfb-proto.h
> +struct rfb_server_cut_text_msg {
These structs are the same, right? Why not just have one of them called `rfb_cut_text_msg`?

2020-09-18 10:59 UTC, any1 commented on src/server.c
> +void _nvnc_server_cut_text(struct nvnc_display* display, char* text, uint32_t len)
Why per display? Should this not be per server?

2020-09-18 10:59 UTC, any1 commented on src/server.c
> +	struct rfb_server_cut_text_msg* msg = calloc(1, size);
This does not need to be heap allocated.

2020-09-18 10:59 UTC, any1 commented on include/neatvnc.h
> +typedef void (*nvnc_client_cut_fn)(struct nvnc_client*, char* data, uint32_t len);
Also, let's call the type `nvnc_cut_text_fn`.

2020-09-18 10:59 UTC, any1 commented on include/neatvnc.h
> +void _nvnc_server_cut_text(struct nvnc_display*, char *text, uint32_t length);
Also, I'd prefer the name `nvnc_send_cut_text`. The names "client cut text" and "server cut text" are implementation details leaking from the protocol.

2020-09-18 12:14 UTC, any1 requested changes
The commit message says "fixes #4", but the correct thing to say is "closes #4". ;)

2020-09-18 12:14 UTC, any1 commented on src/server.c
> +	msg.type = 3;
This should be `RFB_SERVER_TO_CLIENT_SERVER_CUT_TEXT`

2020-09-18 12:14 UTC, any1 commented on src/server.c
> +	LIST_FOREACH_SAFE (client, &server->clients, link, tmp) {
`LIST_FOREACH` will do.

2020-09-18 12:14 UTC, any1 commented on include/common.h
> +	nvnc_cut_text_fn client_cut_fn;
Let's just call this `cut_text_fn`

2020-09-18 12:14 UTC, any1 commented on include/neatvnc.h
> +void nvnc_set_client_cut_fn(struct nvnc* self, nvnc_cut_text_fn fn);
Maybe call this `nvnc_set_cut_text_receive_fn`?

2020-09-18 13:01 UTC, soreau commented
The length argument is necessary because we're not always guaranteed to be dealing with null terminated strings.

2020-09-18 13:22 UTC, any1 approved these changes

2020-09-21 21:15 UTC, merged

2020-09-21 21:16 UTC, any1 commented
Thanks!