Record client hostname and username
any1/neatvnc pull request #80
Opened 2022-10-31 16:11 UTC by lack

- Record peer hostname for each connected client
- Record authenticated username for each connected client

Both of these are best-effort, and may not be available for all clients.

2022-11-03 21:53 UTC, any1 requested changes

2022-11-03 21:53 UTC, any1 commented on include/common.h
> +	char hostname[128];
According to a quick search, I found that the maximum name of a host name is 254 characters. So, best set this to 256.

2022-11-03 21:53 UTC, any1 commented on include/common.h
> +	char username[64];
I used 256 for the maximum username length elsewhere. It's a bit ridiculous, but let's just keep it consistent.

2022-11-03 21:53 UTC, any1 commented on src/server.c
> +	strncpy(client->username, username, sizeof(client->username));
I haven't added `strlcpy` to this project, so we manually zero terminate after `strncpy`.

2022-11-03 21:53 UTC, any1 commented on src/server.c
> +	struct sockaddr_storage storage;
It would be nice to have this extracted to its own function for readability.

2022-11-03 21:53 UTC, any1 commented on src/server.c
> +const char* nvnc_client_get_peer_hostname(const struct nvnc_client* client) {
I wonder if maybe this should just be "nvnc_client_get_hostname".  I'm not sure if I ever properly understood the term "peer" in a network context, but it seems to suggest that two nodes are of equal footing. which they are not in this case.

2022-11-04 09:32 UTC, lack commented
@any1 Thanks for the review!  Addressed all comments.

2022-11-04 09:41 UTC, merged

2022-11-04 09:41 UTC, any1 commented
Thanks!